"""Register export to XLSX.

Shaped like the DepEd SF2 monthly register the school already uses on paper: students
down the side, days across the top, one letter per cell. A file that looks like the
form staff know is a file they will actually check; one that looks like a database
dump gets filed and ignored.

openpyxl is pure Python, so unlike PySide6 and zxing-cpp it carries no glibc or
architecture constraint on the Pi.
"""

from __future__ import annotations

import sqlite3
from datetime import date as Date
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from ..core import corrections

HEAD = Font(bold=True, size=11)
TITLE = Font(bold=True, size=14)
SMALL = Font(size=9, italic=True, color="666666")
CENTRE = Alignment(horizontal="center", vertical="center")

# A corrected cell is tinted rather than merely noted somewhere, because the whole
# point of the audit trail is that a reader can tell at a glance which values came
# from a scan and which a person set afterwards.
CORRECTED = PatternFill("solid", fgColor="FFF3CD")
WEEKEND = PatternFill("solid", fgColor="F2F2F2")
THIN = Side(style="thin", color="BFBFBF")
BOX = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

MONTHS = ("January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December")


def export_register(
    conn: sqlite3.Connection,
    section_id: int,
    year: int,
    month: int,
    path: str | Path,
    *,
    school_name: str = "",
) -> Path:
    """Write one section's month to `path`. Returns the path written."""
    path = Path(path)
    days, rows = corrections.register(conn, section_id, year, month)

    section = conn.execute(
        "SELECT name, grade_level FROM sections WHERE id = ?", (section_id,)
    ).fetchone()
    label = f"{section['grade_level']}-{section['name']}" if section else str(section_id)

    book = Workbook()
    sheet = book.active
    # Excel refuses sheet names over 31 chars or containing []:*?/\ -- a section named
    # by a teacher is user input and will eventually contain one of them.
    sheet.title = f"{label} {MONTHS[month - 1][:3]}"[:31].replace("/", "-")

    sheet["A1"] = school_name or "TRACKIFY"
    sheet["A1"].font = TITLE
    sheet["A2"] = f"Attendance register - {label} - {MONTHS[month - 1]} {year}"
    sheet["A2"].font = HEAD
    sheet["A3"] = (
        "Generated by TRACKIFY. Shaded cells were corrected by a person after "
        "scanning; see the edit log for who and why."
    )
    sheet["A3"].font = SMALL

    header = 5
    sheet.cell(header, 1, "Student").font = HEAD

    for index, day in enumerate(days):
        column = 2 + index
        parsed = Date.fromisoformat(day)
        cell = sheet.cell(header, column, parsed.day)
        cell.font = HEAD
        cell.alignment = CENTRE
        cell.border = BOX
        if parsed.weekday() >= 5:
            cell.fill = WEEKEND
        sheet.column_dimensions[get_column_letter(column)].width = 4

    totals = ("P", "L", "A", "E", "Rate")
    first_total = 2 + len(days)
    for offset, name in enumerate(totals):
        cell = sheet.cell(header, first_total + offset, name)
        cell.font = HEAD
        cell.alignment = CENTRE
        cell.border = BOX
        sheet.column_dimensions[get_column_letter(first_total + offset)].width = 7

    for index, row in enumerate(rows):
        line = header + 1 + index
        sheet.cell(line, 1, row.name).border = BOX

        for column_index, day in enumerate(days):
            cell_data = row.cells[day]
            cell = sheet.cell(line, 2 + column_index, cell_data.letter or "")
            cell.alignment = CENTRE
            cell.border = BOX
            if cell_data.corrected:
                cell.fill = CORRECTED
            elif Date.fromisoformat(day).weekday() >= 5:
                cell.fill = WEEKEND

        for offset, value in enumerate(
            (row.present, row.late, row.absent, row.excused)
        ):
            cell = sheet.cell(line, first_total + offset, value)
            cell.alignment = CENTRE
            cell.border = BOX

        rate_cell = sheet.cell(line, first_total + 4)
        if row.rate is None:
            # Not 0%. A section with nothing recorded has an UNDEFINED rate, and 0%
            # would read as catastrophic attendance rather than as no data.
            rate_cell.value = "-"
        else:
            rate_cell.value = row.rate
            rate_cell.number_format = "0.0%"
        rate_cell.alignment = CENTRE
        rate_cell.border = BOX

    legend = header + len(rows) + 2
    # Letters here, marks on screen. The register staff already use on paper is
    # lettered, and a check character in a spreadsheet depends on the font of whoever
    # opens it -- Excel, LibreOffice, or Google Sheets.
    sheet.cell(legend, 1,
               "P present   L late   A absent   E excused   O online   "
               "(blank) no record   -   on screen: check = present, cross = absent"
               ).font = SMALL
    sheet.cell(legend + 1, 1,
               "Excused days are removed from the rate denominator, not counted as "
               "absent.").font = SMALL

    sheet.column_dimensions["A"].width = 28
    sheet.freeze_panes = sheet.cell(header + 1, 2)

    path.parent.mkdir(parents=True, exist_ok=True)
    book.save(path)
    return path


def default_filename(label: str, year: int, month: int) -> str:
    safe = "".join(c if c.isalnum() or c in "-_" else "-" for c in label)
    return f"attendance-{safe}-{year}-{month:02d}.xlsx"
