"""Write _baked.py so build.bat can compile the QR secret into the exe.

Run only by build.bat, and the file it writes is deleted straight after the build.
_baked.py is gitignored: the secret must never reach the repository.

Baking the secret is a deliberate trade-off. School staff never have to be told it or
type it, which is why it was chosen; the costs are that the value is recoverable from
the binary by anyone determined, and that rotating it means rebuilding and handing out
a new exe. Anyone holding the exe can mint a valid code for any LRN, so treat the
distributed copy as a key.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generate import read_secret

TARGET = Path(__file__).resolve().parent / "_baked.py"


def main() -> int:
    # Explicitly NOT _baked.py's own value: read from the environment or .env, so a
    # rebuild always picks up the current secret rather than recycling a stale bake.
    if TARGET.exists():
        TARGET.unlink()

    secret = read_secret(Path(__file__).resolve().parent)
    if not secret:
        print("TRACKIFY_QR_SECRET not found in the environment or any .env.",
              file=sys.stderr)
        print("The exe would be built unable to sign anything.", file=sys.stderr)
        return 1

    TARGET.write_text(
        '"""Generated by bake.py at build time. Never commit this file."""\n'
        f"SECRET = {secret!r}\n",
        encoding="utf8",
    )
    print(f"Baked the secret into {TARGET.name} ({len(secret)} chars).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
